#!/bin/bash
# Rose Pine Moon. For your hyprland gradient instead, use:
# active_color=gradient(top_left=0xff33ccff,bottom_right=0xff00ff99)
options=(
  style=round
  width=4.0
  hidpi=on
  active_color=0xffc4a7e7
  inactive_color=0xff232136
)
borders "${options[@]}"
